# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='lastrev_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='user_retained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stackoverflowanswer',
            name='parent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
