# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedRedditPost',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=10000)),
                ('score', models.IntegerField()),
                ('is_root', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=50)),
                ('user_rep', models.IntegerField()),
                ('user_badges', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('discourse_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WikiScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('day_prior_rev_id', models.CharField(max_length=50)),
                ('day_prior_ores_score', models.IntegerField()),
                ('day_of_rev_id', models.CharField(max_length=50)),
                ('day_of_ores_score', models.IntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.WikiLink')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='wiki_links',
            field=models.ManyToManyField(to='portal.WikiLink'),
        ),
    ]
