# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170728_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=10000)),
                ('score', models.IntegerField()),
                ('is_root', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=50)),
                ('user_rep', models.IntegerField()),
                ('user_badges', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('user_comment_karma', models.IntegerField()),
                ('user_link_karma', models.IntegerField()),
                ('user_created_utc', models.DateTimeField()),
                ('user_is_mod', models.BooleanField()),
                ('wiki_links', models.ManyToManyField(to='portal.WikiLink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='context',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='score',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='user_badges',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='user_rep',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='wiki_links',
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='redditpost_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.RedditPost'),
            preserve_default=False,
        ),
    ]
