# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170822_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledredditthread',
            old_name='num_pageviews',
            new_name='num_wiki_pageviews',
        ),
        migrations.RenameField(
            model_name='sampledredditthread',
            old_name='num_pageviews_prev_week',
            new_name='num_wiki_pageviews_prev_week',
        ),
        migrations.RenameField(
            model_name='sampledstackoverflowpost',
            old_name='num_pageviews_prev_week',
            new_name='num_wiki_pageviews_prev_week',
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_wiki_pageviews',
            field=models.IntegerField(default=0),
        ),
    ]
