# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170728_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='wiki_links',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='redditpost_ptr',
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='body',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='context',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='uid',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_badges',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_comment_karma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_created_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_is_mod',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_link_karma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_rep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='wiki_links',
            field=models.ManyToManyField(to='portal.WikiLink'),
        ),
        migrations.DeleteModel(
            name='RedditPost',
        ),
    ]
