# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170822_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_other_answers',
            field=models.IntegerField(default=0),
        ),
    ]
