# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170728_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='user_badges',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='user_rep',
        ),
    ]
