# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_sampledstackoverflowpost_num_other_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_new_editors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_new_editors_retained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_new_editors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_new_editors_retained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='num_wiki_pageviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='num_wiki_pageviews_prev_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='num_wiki_pageviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='num_wiki_pageviews_prev_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
