# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170728_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
    ]
