# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170824_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_question_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='question_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title',
            field=models.CharField(default='', max_length=1182),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_coleman_liau_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_lexicon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_percent_punctuation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_percent_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_percent_uppercase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_starts_capitalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='title',
            field=models.CharField(default='', max_length=1182),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='owner_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='parent_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='accepted_answer_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='owner_user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
