# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadLog',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
