# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_threadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_is_suspended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_created_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
