# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170825_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='sample_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='sample_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='has_good_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='has_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='has_good_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='has_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
