# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170728_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
