# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20170826_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='sample_num',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='sample_num',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
