# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20170728_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedredditpost',
            name='user_is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_comment_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_is_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_link_karma',
            field=models.IntegerField(default=0),
        ),
    ]
