# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20170827_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledredditthread',
            old_name='wiki_content_analyzed',
            new_name='all_revisions_pulled',
        ),
        migrations.RenameField(
            model_name='sampledstackoverflowpost',
            old_name='wiki_content_analyzed',
            new_name='all_revisions_pulled',
        ),
        migrations.AddField(
            model_name='revision',
            name='err_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wikilink',
            name='err_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revision',
            name='editcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='lastrev_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
