# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20170728_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampledRedditPost',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=10000)),
                ('score', models.IntegerField()),
                ('is_root', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('user_comment_karma', models.IntegerField(default=0)),
                ('user_link_karma', models.IntegerField(default=0)),
                ('user_created_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_is_mod', models.BooleanField(default=False)),
                ('user_is_suspended', models.BooleanField(default=False)),
                ('user_is_deleted', models.BooleanField(default=False)),
                ('wiki_links', models.ManyToManyField(to='portal.WikiLink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackOverflowPost',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=10000)),
                ('score', models.IntegerField()),
                ('is_root', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('user_reputation', models.IntegerField(default=0)),
                ('user_created_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('wiki_links', models.ManyToManyField(to='portal.WikiLink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
