# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20170827_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='has_b_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='has_c_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='has_b_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='has_c_wiki_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
