# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_sampledredditpost_stackoverflowpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampledRedditPost',
            new_name='SampledRedditThread',
        ),
    ]
