# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20170731_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionScore',
            fields=[
                ('rev_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='wikiscore',
            name='link',
        ),
        migrations.DeleteModel(
            name='WikiScore',
        ),
        migrations.AddField(
            model_name='wikilink',
            name='day_of',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='day_of', to='portal.RevisionScore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikilink',
            name='day_prior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='day_prior', to='portal.RevisionScore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikilink',
            name='week_after',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='week_after', to='portal.RevisionScore'),
            preserve_default=False,
        ),
    ]
