# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20170731_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedredditpost',
            name='wiki_content_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='wiki_content_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stackoverflowpost',
            name='wiki_content_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
