# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20170830_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='year',
        ),
        migrations.RemoveField(
            model_name='sampledstackoverflowpost',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sampledstackoverflowpost',
            name='year',
        ),
    ]
