# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20170731_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
