# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_sampledredditthread_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledredditthread',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wikilink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
