# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20170731_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowpost',
            name='context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
