# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20170831_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_includes_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_includes_question_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='title_includes_question_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_includes_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_includes_question_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_includes_question_mark',
            field=models.BooleanField(default=False),
        ),
    ]
