# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20170902_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_sentiment_polarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_sentiment_subjectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='title_sentiment_polarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='title_sentiment_subjectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_sentiment_polarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_sentiment_subjectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_sentiment_polarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='title_sentiment_subjectivity',
            field=models.IntegerField(default=0),
        ),
    ]
