# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20170731_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSpecificWikiLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='wikilink',
            name='day_of',
        ),
        migrations.RemoveField(
            model_name='wikilink',
            name='day_prior',
        ),
        migrations.RemoveField(
            model_name='wikilink',
            name='week_after',
        ),
        migrations.AddField(
            model_name='revisionscore',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='revisionscore',
            name='wiki_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.WikiLink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postspecificwikilink',
            name='day_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of', to='portal.RevisionScore'),
        ),
        migrations.AddField(
            model_name='postspecificwikilink',
            name='day_prior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_prior', to='portal.RevisionScore'),
        ),
        migrations.AddField(
            model_name='postspecificwikilink',
            name='week_after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_after', to='portal.RevisionScore'),
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='post_specific_wiki_links',
            field=models.ManyToManyField(to='portal.PostSpecificWikiLink'),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='post_specific_wiki_links',
            field=models.ManyToManyField(to='portal.PostSpecificWikiLink'),
        ),
        migrations.AddField(
            model_name='stackoverflowpost',
            name='post_specific_wiki_links',
            field=models.ManyToManyField(to='portal.PostSpecificWikiLink'),
        ),
    ]
