# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20170902_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
