# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20170731_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StackOverflowPost',
            new_name='SampledStackOverflowPost',
        ),
    ]
