# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20170801_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedredditpost',
            name='user_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='user_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='user_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
