# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_sampledstackoverflowpost_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='user_retained_180',
            field=models.BooleanField(default=False),
        ),
    ]
