# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20170801_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionscore',
            old_name='rev_id',
            new_name='revid',
        ),
        migrations.AddField(
            model_name='wikilink',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wikilink',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wikilink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
