# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_revision_user_retained_180'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_new_editors_retained_180',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_new_editors_retained_prev_week_180',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_new_editors_retained_180',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_new_editors_retained_prev_week_180',
            field=models.IntegerField(default=0),
        ),
    ]
