# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20170909_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikilink',
            name='alt_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
