# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20170802_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedredditpost',
            name='has_wiki_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotatedredditpost',
            name='num_wiki_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='has_wiki_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_wiki_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='has_wiki_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_wiki_links',
            field=models.IntegerField(default=0),
        ),
    ]
