# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20180314_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
