# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20170802_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedredditpost',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
