# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_sampledstackoverflowpost_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='owner_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
