# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20170802_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='post_specific_wiki_links',
        ),
        migrations.RemoveField(
            model_name='annotatedredditpost',
            name='wiki_links',
        ),
        migrations.DeleteModel(
            name='AnnotatedRedditPost',
        ),
    ]
