# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20170802_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
