# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_sampledredditthread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledredditthread',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
