# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20170802_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='user_info_processed',
            field=models.BooleanField(default=False),
        ),
    ]
