# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_sampledredditthread_user_info_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
