# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20170803_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='num_pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikilink',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wikilink',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
