# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20170803_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledredditthread',
            name='body',
            field=models.CharField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='body',
            field=models.CharField(max_length=30000),
        ),
    ]
