# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20170804_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='tags_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='tags',
            field=models.ManyToManyField(to='portal.Tag'),
        ),
    ]
