# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20170804_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='tags_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
