# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20170808_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='wiki_content_error',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='wiki_content_error',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='msg',
            field=models.CharField(max_length=500),
        ),
    ]
