# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20170810_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('created_utc', models.IntegerField()),
                ('subreddit', models.CharField(max_length=21)),
                ('author', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=206)),
                ('url', models.CharField(max_length=6843)),
                ('num_comments', models.IntegerField()),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=329)),
                ('selftext', models.CharField(max_length=59994)),
                ('saved', models.BooleanField()),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gilded', models.IntegerField()),
                ('stickied', models.BooleanField()),
                ('retrieved_on', models.IntegerField()),
                ('over_18', models.BooleanField()),
                ('thumbnail', models.CharField(max_length=80)),
                ('subreddit_id', models.CharField(max_length=8)),
                ('hide_score', models.BooleanField()),
                ('link_flair_css_class', models.CharField(max_length=61)),
                ('author_flair_css_class', models.CharField(max_length=92)),
                ('archived', models.BooleanField()),
                ('is_self', models.BooleanField()),
                ('permalink', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=9)),
                ('author_flair_text', models.CharField(max_length=89)),
                ('quarantine', models.BooleanField()),
                ('link_flair_text', models.CharField(max_length=67)),
                ('distinguished', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='StackOverflowUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=30)),
                ('about_me', models.CharField(max_length=5999)),
                ('age', models.CharField(max_length=4)),
                ('creation_date', models.DateTimeField()),
                ('last_access_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('reputation', models.IntegerField()),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('profile_image_url', models.CharField(max_length=105)),
                ('website_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sampledredditthread',
            name='body',
            field=models.CharField(max_length=58431),
        ),
        migrations.AlterField(
            model_name='sampledstackoverflowpost',
            name='body',
            field=models.CharField(max_length=58431),
        ),
    ]
