# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20170811_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_css_class',
            field=models.CharField(blank=True, max_length=92, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_text',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='distinguished',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_css_class',
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_text',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
