# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20170811_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflowquestion',
            name='view_count',
        ),
    ]
