# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_remove_stackoverflowquestion_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflowanswer',
            name='accepted_answer_id',
        ),
        migrations.RemoveField(
            model_name='stackoverflowanswer',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='stackoverflowanswer',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='stackoverflowanswer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='stackoverflowanswer',
            name='view_count',
        ),
        migrations.AddField(
            model_name='stackoverflowquestion',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
