# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20170813_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='community_owned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='last_editor_display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='last_editor_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='accepted_answer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='community_owned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='last_editor_display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='last_editor_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
