# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20170813_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowquestion',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=5999, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
