# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20170813_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='time_since_user_creation',
        ),
        migrations.RemoveField(
            model_name='sampledstackoverflowpost',
            name='time_since_user_creation',
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='seconds_since_user_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='seconds_since_user_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
