# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20170814_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_num_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_num_links',
            field=models.IntegerField(default=0),
        ),
    ]
