# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_auto_20170814_2142'),
        ('portal', '0049_auto_20170815_0228'),
    ]

    operations = [
    ]
