# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_merge_20170814_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='body_flesch_kincaid_grade',
        ),
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='title_flesch_kincaid_grade',
        ),
        migrations.RemoveField(
            model_name='sampledstackoverflowpost',
            name='body_flesch_kincaid_grade',
        ),
    ]
