# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_auto_20170814_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_lexicon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='body_sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='title_lexicon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledredditthread',
            name='title_sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_lexicon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='body_sentence_count',
            field=models.IntegerField(default=0),
        ),
    ]
