# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_auto_20170814_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='display_name',
            field=models.CharField(max_length=36),
        ),
    ]
