# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_auto_20170815_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledredditthread',
            name='has_good_wiki_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledstackoverflowpost',
            name='has_good_wiki_link',
            field=models.BooleanField(default=False),
        ),
    ]
