# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_auto_20170815_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('revid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=-1)),
                ('user', models.CharField(max_length=100)),
                ('editcount', models.IntegerField(default=0)),
                ('registration', models.DateTimeField()),
                ('minor_edit', models.BooleanField(default=True)),
                ('wiki_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.WikiLink')),
            ],
        ),
        migrations.RemoveField(
            model_name='postspecificwikiscores',
            name='day_of',
        ),
        migrations.RemoveField(
            model_name='postspecificwikiscores',
            name='day_prior',
        ),
        migrations.RemoveField(
            model_name='postspecificwikiscores',
            name='week_after',
        ),
        migrations.RemoveField(
            model_name='revisionscore',
            name='wiki_link',
        ),
        migrations.RemoveField(
            model_name='sampledredditthread',
            name='post_specific_wiki_links',
        ),
        migrations.RemoveField(
            model_name='sampledstackoverflowpost',
            name='post_specific_wiki_links',
        ),
        migrations.DeleteModel(
            name='PostSpecificWikiScores',
        ),
        migrations.DeleteModel(
            name='RevisionScore',
        ),
    ]
