# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_auto_20170817_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
